### ISSUE TITLE
Fresh install fails: 3 chained init bugs + iotToken refresh is broken (account without received shares)

### ISSUE THREAD

**Issue by lempech** [mikey0000/Mammotion-HA#756]
## Summary

Fresh install of this integration with a brand-new Mammotion account (single owned device, **no shared devices received**) fails to function in 4 chained ways. Two bugs are in `pymammotion` (one of which silently kills the integration after the iotToken expires), two are in this component. The first three are blocking `async_setup_entry`; the fourth blocks the refresh loop indefinitely.

Patches for the first three are below. The fourth (iotToken refresh) is the actual show-stopper and I couldn't safely fix it locally.

## Environment

- Home Assistant Core **2026.5.4** on HAOS (Raspberry Pi 5 64-bit)
- `custom_components/mammotion` **0.5.47**
- `pymammotion` versions tested: **0.7.115** (manifest-pinned), **0.7.128**, **0.7.129**
- Device: **LUBA 3 AWD 3000** (firmware **2.3.23.19**)
- Account: freshly created, single owned device, **no incoming device shares**, EU region (`areaCode: BEL`)
- WiFi + BLE adapter present (`prefer_ble_over_wifi: true`, `use_wifi: true`)

## Bug 1 — Aliyun MQTT auth loop (pymammotion 0.7.115)
With the manifest-pinned `pymammotion==0.7.115`, the integration enters an infinite MQTT bind/refresh loop within ~2 hours of a successful first fetch:

```
ERROR  pymammotion.transport.aliyun_mqtt  Aliyun account bind failed (code=2043): check iotToken failed
WARN   pymammotion.transport.aliyun_mqtt  Aliyun bind token expired — attempting credential refresh
ERROR  pymammotion.aliyun.cloud_gateway   {'code': 2401, 'localizedMsg': 'refreshToken invalid!!'}
WARN   pymammotion.client                 Aliyun refreshToken exhausted — escalating to full re-login
ERROR  pymammotion.client                 Full re-login failed for MQTT transport
…
LoginFailedError: Aliyun refreshToken rejected 2 times within 120s — re-authentication required
```

Counts over ~15 min: **147× `code=2043`, 144× full re-login attempts, all failed.** Deleting and re-adding the config entry produces the same loop within seconds.

Fixed in 0.7.116+ (zero `code=2043` after upgrade), so the 0.7.115 pin in `manifest.json` is an immediate blocker for new users.

## Bug 2 — `MammotionHTTP.devices_shared_info` is read but never initialized (pymammotion 0.7.116 → 0.7.128)

After bumping to 0.7.128, bootstrap crashes:

```
File "pymammotion/client.py", line 1589, in _bootstrap_mammotion_mqtt
    shared_resp = await mammotion_http.get_user_shared_device_page()
File "pymammotion/http/http.py", line 554, in get_user_shared_device_page
    self.devices_shared_info = response.data if response.data else self.devices_shared_info
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MammotionHTTP' object has no attribute 'devices_shared_info'
```

The attribute is **read** in the `else` branch but **never initialized** in `__init__`. When `/user-server/v1/share/device/page` returns empty `data` (a fresh single-owner account), the `else` executes and raises. Confirmed by `pip download` + grep on every release from 0.7.116 to 0.7.128.

**Fix:**
```diff
- self.devices_shared_info = response.data if response.data else self.devices_shared_info
+ self.devices_shared_info = response.data if response.data else getattr(self, "devices_shared_info", None)
```

Or initialize `self.devices_shared_info = None` in `MammotionHTTP.__init__`.

(Also, 0.7.129 looks like it left a half-finished refactor — the bug is still present and the call site looks broken in a different way; 0.7.128 is the highest version usable until both are fixed.)

## Bug 3 — Multiple coordinators dereference `mowing_device` without null-check (Mammotion-HA 0.5.47)

After patching Bug 2, `async_setup_entry` still fails:

```
File "custom_components/mammotion/coordinator.py", line 1580, in __init__
    self.data = mowing_device.report_data.maintenance
                ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'report_data'
```

The exception confirms `mowing_device` itself is **None** — `self.manager.get_device_by_name(self.device_name)` returns nothing because the manager has no entry yet (no MQTT frame received from the mower; mine was docked / idle at install time).

Hit on **every reload** of the entry while the mower is asleep. Four subclasses share the pattern:

- `coordinator.py:1579-80` (`MammotionMaintenanceUpdateCoordinator`) — dereferences `mowing_device.report_data.maintenance`
- `coordinator.py:1795-96` (`MammotionMapUpdateCoordinator`) — dereferences `mowing_device.mower_state`
- `coordinator.py:1653` and `:1882` — assigns `self.data = mowing_device` (no crash, but `self.data` ends up `None` and downstream code probably trips)
- `coordinator.py:157` is **safe** (uses local `mower_device` and a different code path — note the spelling)

**Fix** (applied locally, all 4 setup successfully after this):

```diff
# coordinator.py:1579
-        if self.data is None:
+        if self.data is None and mowing_device is not None and mowing_device.report_data is not None:
             self.data = mowing_device.report_data.maintenance

# coordinator.py:1795
-        if self.data is None:
+        if self.data is None and mowing_device is not None and mowing_device.mower_state is not None:
             self.data = mowing_device.mower_state

# coordinator.py:1653 and :1882
-        if self.data is None:
+        if self.data is None and mowing_device is not None:
             self.data = mowing_device
```

Letting `self.data` stay `None` at boot is safe — the coordinator's `_on_state_changed` will populate it once the first device snapshot arrives.

## Bug 4 (THE SHOW-STOPPER) — `list_binding_by_account` returns 401 after iotToken expires, silently kills the integration

After applying patches for bugs 1-3, `async_setup_entry` finally succeeds. But the refresh loop now plants on:

```
ERROR custom_components.mammotion  Unexpected error fetching mammotion data
  File "custom_components/mammotion/coordinator.py", line 1665, in _async_update_data
    assert device is not None
           ^^^^^^^^^^^^^^^^^^
AssertionError
```

The manager is empty so `self.manager.get_device_by_name(self.device_name)` returns None, and the assert fires every refresh interval (~60s).

Tracing back, this is the underlying log line that explains it:

```
WARN  pymammotion.client  restore_credentials: new-device discovery failed (Aliyun)
  File "pymammotion/client.py", line 1447, in _restore_aliyun
  File "pymammotion/aliyun/cloud_gateway.py", line 678, in list_binding_by_account
pymammotion.aliyun.exceptions.CloudSetupError: Error listing devices by account (code=401): request auth error.
```

The `iotToken` stored in the config entry expires (~30-60 min after OAuth). `list_binding_by_account` is called with the stale token and the Aliyun gateway returns `code=401`. The `try/except` in `_restore_aliyun` swallows the failure as a warning, so the integration does not crash — **but the device is never registered in the manager, no MQTT subscribe ever happens for the Luba's topics, and zero report frames are ever received**.

Symptoms observed: 4× HTTP 401, 9× refresh AssertionError over a 10-minute window. **Zero MQTT messages received from the mower the entire session**, even after sending a "Start mowing" command from the official Mammotion mobile app (which the Luba executed normally, confirming the device is healthy and online — just unreachable from this integration).

The integration cannot recover on its own. The only workaround I found is delete + re-add the config entry, which gives ~30-60 min of fresh tokens before sliding back into 401.

This is the actual blocker for daily use. Bugs 1-3 can be patched locally; bug 4 needs an upstream fix in `pymammotion`'s token refresh path (presumably `_full_relogin` or `token_manager.force_refresh` should be invoked when `list_binding_by_account` returns 401, but currently the `except Exception: _logger.warning(...)` just swallows it).

## Steps to reproduce

1. Create a brand-new Mammotion account, or one with no received share invitations.
2. Bind one LUBA-series device via the mobile app.
3. Leave the mower docked / idle.
4. Install this integration via HACS, add the config entry.
5. Observe sequential failures matching bugs 1 → 2 → 3 → 4 as you work around each.

## Recommended fix sequence

1. Cut a `pymammotion` release that:
   - initializes `MammotionHTTP.devices_shared_info = None` in `__init__` (Bug 2);
   - retries `list_binding_by_account` after invoking `force_refresh` on 401, instead of swallowing as warning (Bug 4).
2. Bump the `pymammotion` requirement in `manifest.json` to that release (also fixes Bug 1 for new users).
3. Add `mowing_device is not None` / `report_data is not None` / `mower_state is not None` guards in the four coordinator subclasses (Bug 3).

Happy to open PRs — wanted to land the full diagnostic in one place first.

Thanks for the work on this integration.

### What Mammotion device are you using?

Luba 3 AWD 3000

### What version of the Mammotion integration are you using?

v0.5.47

### What version of Home Assistant Core are you running?

Home Assistant Core **2026.5.4** on HAOS (Raspberry Pi 5 64-bit)

**Comment by lempech** [comment]
## Update — root cause is actually different (shared/secondary account scenario)

After deeper investigation calling the Aliyun IoT API directly with the credentials cached in the config entry, I found that **bug 4 is a symptom, not the root cause**. The real issue is that this integration does not work for **shared/secondary accounts** — which is, per Mammotion's own recommendation, how users *should* set up Home Assistant integration to avoid being kicked out of the mobile app.

### Evidence

With fresh tokens (immediately after a `delete + re-add` cycle, so iotToken cannot be blamed) the three Aliyun IoT calls return:

```
list_binding_by_account     → code=200, total=0, data=[]
get_device_properties(iot_id) → code=2063  "iotId does not exist"
get_device_status(iot_id)     → code=29004 "device is unbind"
```

But the config entry was created successfully via OAuth, and the Mammotion HTTP API (`api-iot-business.cloud-eu.mammotion.com`) returned **one device** in `mammotion_device_records`:

```json
[
  {
    "iot_id": "<redacted>",
    "product_key": "uY54W5rM8YH",
    "device_name": "Luba-VAFJ7LH5",
    "owned": 0,        ← key field
    "status": 1,
    "bind_time": <timestamp>
  }
]
```

The device record appears in the **`share/device/page`** branch (the `owned: 0` corresponds to the request body `{"owned": 0, ...}` filtering for shared/incoming devices). It does **NOT** appear in `device/list` (`mammotion_device_list: []`) nor in Aliyun's `list_binding_by_account` (`total: 0`).

### Why this is the recommended setup

Mammotion's mobile app does not support concurrent sessions for the same account. If a user logs into Home Assistant with their primary account, the mobile app is kicked out. The Mammotion-recommended workaround is to create a **secondary email account, share the mower from the primary account to the secondary, and use the secondary in Home Assistant**. This is exactly what I did.

In this (recommended) setup:
- The secondary account has access to the device through the **share** mechanism (`/user-server/v1/share/device/page` returns it)
- But the secondary account is **not bound as owner** at the Aliyun IoT level → it has no MQTT subscribe rights on the device topics (`/sys/{productKey}/{deviceName}/...`)
- `pymammotion` only iterates `get_user_device_list()` (owned) when populating its local manager — it never registers shared devices for MQTT subscription

### Consequences for this integration

- The manager stays empty → `MammotionMaintenanceUpdateCoordinator` (and the other 3 coordinator subclasses) hit the `NoneType` bugs from my original report (bugs 3)
- The `_async_update_data` `assert device is not None` always fires (bug 4 in my original report)
- `restore_credentials → list_binding_by_account → 401` is **not** a refresh-token problem — it's the same iotToken simply not having any device to query. The "401 request auth error" is in fact Aliyun saying "this account can't query that device" but pymammotion classifies it as auth failure and triggers an unhelpful re-login loop.

### Suggested fix

`pymammotion.client._bootstrap_mammotion_mqtt` / `_restore_aliyun` should:

1. After fetching `get_user_shared_device_page()`, **register the shared devices** in the local manager and MQTT subscription path, not only the `owned` ones.
2. Subscribe to the **owner's** topic namespace (`/sys/{owner_productKey}/{owner_deviceName}/...`) but with the **secondary account's identity_id**. The Aliyun IoT permission model does allow this — the share mechanism grants the secondary account read+write rights on the owner's topics — but pymammotion must explicitly request the subscription under the owner's productKey/deviceName.
3. Stop classifying 401 from `list_binding_by_account` as a "refresh token failure" when in fact it's an "account has no devices on Aliyun IoT" case. A clearer log message + skip-not-loop would help users diagnose the underlying setup issue.

### Reproduction

1. Create or use a **secondary** Mammotion account (e.g. for use in HA, to keep the mobile app logged in to the primary).
2. From the **primary** account, share the LUBA to the secondary.
3. In HA, set up this integration with the secondary account credentials. → Setup completes, 77 entities created, but all stay frozen / unavailable, and `home-assistant.log` fills with bugs 3+4 + 401 / 2043 / 2401 loops.

This is the **recommended** Mammotion setup for HA users, so I think this should be treated as a high-priority bug rather than a corner case.

Happy to test patches.

**Comment by mikey0000** [comment]
Can you try the latest beta please, pretty sure I may have addressed this issue already

**Comment by lempech** [comment]
## ✅ Fixed — confirmed working

Upgraded to **Mammotion-HA v0.6.1 + pymammotion 0.7.131** today, removed all my local patches, restarted HA.

Result:
- All 4 original bugs gone (no `Error setting up entry`, no `AttributeError NoneType`, no `AssertionError`, no `devices_shared_info` crash)
- No Aliyun loop (`code=2043`, `refreshToken invalid`, `iot biz error`) — gone
- **77+ entities updating live**, including the IoT-properties ones (`lawn_mower.state`, `battery`, `mode_activite`, etc.) that were frozen on the secondary/shared account
- Only one residual warning: `VioState: unknown value 172 — falling back to UNKNOWN` (clean fallback, non-blocking)

The shared-account scenario from my second comment is **also fully fixed** — telemetry properties update correctly on a non-owner account too.

Thanks for the quick turnaround 🙏 — closing on my end.

**Comment by mikey0000** [comment]
No worries, thanks for the bug report

**Comment by ckirches** [comment]
I am seeing this again with a fresh install and a Yuku Mini 2.
My login works when installing the integration.

```2026-08-0
8 17:10:36.444 ERROR (MainThread) [pymammotion.transport.aliyun_mqtt] Aliyun account bind failed (code=2043): {'code': 2043, 'id': 'msgid1', 'message': 'check iotToken failed'}
2026-08-08 17:10:36.446 WARNING (MainThread) [pymammotion.transport.aliyun_mqtt] Aliyun bind token expired — attempting credential refresh: Aliyun IoT token rejected by broker (bind_reply 2043) — token needs refresh
2026-08-08 17:10:36.446 WARNING (MainThread) [pymammotion.client] Aliyun bind rejected — attempting targeted credential refresh
2026-08-08 17:10:36.783 WARNING (MainThread) [pymammotion.client] Aliyun refreshToken exhausted — escalating to full re-login
```

This is with 0.6.3.

Repeats ~600 times and nothing works.

**Comment by mikey0000** [comment]
Have you updated the firmware recently? You'll need to reconfigure. Also try the latest beta please
