### ISSUE TITLE
'NoneType' object has no attribute 'preference'

### ISSUE THREAD

**Issue by nijel** [mikey0000/Mammotion-HA#122]
### The problem

After upgrading from 0.1.24 to 0.1.28:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/__init__.py", line 59, in async_setup_entry
    await mammotion_coordinator.async_setup()
  File "/config/custom_components/mammotion/coordinator.py", line 112, in async_setup
    device.preference = preference
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'preference'
```

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.28

### What version of Home Assistant Core are you running?

core-2024.9.1

**Comment by mikey0000** [comment]
I'm running into this as well, a, simple reload fixes it for now.

**Comment by nijel** [comment]
Removing and adding it back fixed it also.

**Comment by mikey0000** [comment]
Found the problem, should be fixed in 0.1.29
