### ISSUE TITLE
Error after update to v0.1.21

### ISSUE THREAD

**Issue by thallth** [mikey0000/Mammotion-HA#114]
### The problem

2024-09-06 23:26:36.150 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Luba-VSMLYBZC for mammotion
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/mammotion/__init__.py", line 59, in async_setup_entry
await mammotion_coordinator.async_setup()
File "/config/custom_components/mammotion/coordinator.py", line 129, in async_setup
elif device.ble():
^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ble'

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.21

### What version of Home Assistant Core are you running?

Core-2024.9.1

**Comment by mikey0000** [comment]
Please try and reconfigure, that should resolve the issue.

7/09/2024 9:38:16 am thallth ***@***.***>:

**Comment by mikey0000** [comment]
There was a bug in a previous version that caused this from what I've gathered from other bug reports.

**Comment by thallth** [comment]
When doing reconfiguration, is says: „Reconfiguration successful“, but the bug remains.
How can I help further debugging?

**Comment by mikey0000** [comment]
I assume your WiFi only? If so remove your mower and readd on the latest version. Sorry for the inconvenience. This should correctly set the flag

**Comment by thallth** [comment]
Yes Wifi only.
Do you think it can also be fixed without requiring the user to remove and delete everything?
I would assume I‘m not the only one running into this..?

**Comment by mikey0000** [comment]
Yeah Im pretty sure I addressed it which will come in the next release. This is still very much in alpha/heavy development and users should expect instability and having to remove/re-add and so on. You can wait for the next release or remove and readd. Up to you.

**Comment by rasssta** [comment]
Can confirm that removing and re-adding works.

**Comment by thallth** [comment]
re-adding also worked for me

**Comment by thallth** [comment]
re
