### PR TITLE
Fix crash without Bluetooth availability

### LINKED ISSUE #105: Failed setup after upgrade to 0.1.20
### The problem

The integration fails to start now:

```
2024-09-04 07:55:41.920 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Luba-XXXXXX for mammotion
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/__init__.py", line 59, in async_setup_entry
    await mammotion_coordinator.async_setup()
  File "/config/custom_components/mammotion/coordinator.py", line 125, in async_setup
    elif device.ble():
         ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ble'
```

Not using Bluetooth at all, only Wi-Fi.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.20

### What version of Home Assistant Core are you running?

core-2024.8.3

### PR DESCRIPTION
**Pull request by nijel**
### **User description**
Fixes #105

___

### **Description**
- Fixes a crash that occurs when Bluetooth is not available by using the `ble_device` variable.
- Enhances error handling during the setup of the Mammotion lawn mower.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>coordinator.py</strong><dd><code>Fix crash when Bluetooth is not available</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

custom_components/mammotion/coordinator.py
<li>Replaced <code>device.ble()</code> check with <code>ble_device</code> variable.<br> <li> Improved error handling for device setup.<br>

</details>

  </td>
  <td><a href="https://github.com/mikey0000/Mammotion-HA/pull/106/files#diff-f8a4a06ede7f30cde21a849be8db19504f7080576f20551e2d0a9c5a7d1d2756">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
</table></td></tr></tr></tbody></table>

### CODE REVIEW

**Comment by mikey0000** [comment]
This doesn't solve the problem really, as device is None, the problem seems to be with the config data. Can you try reconfigure to see if that fixes it?

**Comment by nijel** [comment]
Yes, this doesn't resolve the problem, but makes the integration display an error instead of crashing.

**Comment by mikey0000** [comment]
Thanks for the PR, The situation was created due to CONF_USE_WIFI being set wrong, even so device shouldn't be null, as it gets created based on credentials, so what happened was no credentials nor bluetooth device were passed in.

So a better check would be to check if device is None then abort
