### ISSUE TITLE
Camera entity does not provide video stream

### ISSUE THREAD

**Issue by quantummobile** [mikey0000/Mammotion-HA#671]
### The problem

I just get this image instead of video stream. Entity ID is camera.minis_none. SO I suppose there is something wrong, iust don't know what. Camera works flawlessly in Mammotion app.
<img width="1022" height="562" alt="Image" src="https://github.com/user-attachments/assets/cd013c6e-7f2d-4426-8f5e-e0c973a96595" />

### What Mammotion mower are you using?

Yuka mini

### What version of the Mammotion integration are you using?

0.5.28

### What version of Home Assistant Core are you running?

2026.4.4

**Comment by Penny2912** [comment]
Same here

**Comment by Guigui37** [comment]
Same here, I have just installed the integration, I thought that it was "normal" ...
0.5.28 on 2026.4.4 too.
Same screen on the HASS Android App, and on the WebUI on a computer, I have this:
" Failed to start WebRTC stream: WebRTC negotiation failed "

**Comment by mikey0000** [comment]
Doesn't work in Firefox

**Comment by mikey0000** [comment]
Also something changed as it was working

**Comment by quantummobile** [comment]
Also this entity is no longer available: button.minis_start_camera_on_mower
Maybe the two issues are related?

<img width="579" height="142" alt="Image" src="https://github.com/user-attachments/assets/de327176-91e5-4f5b-b6e7-877cd7d7f79e" />

**Comment by quantummobile** [comment]
> Doesn't work in Firefox

I'm using native app or Brave browser - camera doesn't work on either one.

**Comment by mikey0000** [comment]
> Also this entity is no longer available: button.minis_start_camera_on_mower Maybe the two issues are related?
> 
> <img alt="Image" width="579" height="142" src="https://private-user-images.githubusercontent.com/47085307/585855130-de327176-91e5-4f5b-b6e7-877cd7d7f79e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzc1MzI2OTksIm5iZiI6MTc3NzUzMjM5OSwicGF0aCI6Ii80NzA4NTMwNy81ODU4NTUxMzAtZGUzMjcxNzYtOTFlNS00ZjViLWI2ZTctODc3Y2Q3ZDdmNzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDMwVDA2NTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMmY5NGMzYzc1MjgxMmI5NzI4YTljNzI0YmExNDJiNmQxYjQwYmIyZWVjNGI2NmVhMGQ4MGMzMmY5ZjdjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.ZFc92OhYxL1yqSeaXkPAxsck-y-ZMGN9yHq3GMd306Q">

Removed as wasn't necessary and didn't work anyway

**Comment by quantummobile** [comment]
> > Also this entity is no longer available: button.minis_start_camera_on_mower Maybe the two issues are related?
> > <img alt="Image" width="579" height="142" src="https://private-user-images.githubusercontent.com/47085307/585855130-de327176-91e5-4f5b-b6e7-877cd7d7f79e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzc1MzI2OTksIm5iZiI6MTc3NzUzMjM5OSwicGF0aCI6Ii80NzA4NTMwNy81ODU4NTUxMzAtZGUzMjcxNzYtOTFlNS00ZjViLWI2ZTctODc3Y2Q3ZDdmNzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDMwVDA2NTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMmY5NGMzYzc1MjgxMmI5NzI4YTljNzI0YmExNDJiNmQxYjQwYmIyZWVjNGI2NmVhMGQ4MGMzMmY5ZjdjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.ZFc92OhYxL1yqSeaXkPAxsck-y-ZMGN9yHq3GMd306Q">
> 
> Removed as wasn't necessary and didn't work anyway

Alright. What about the camera stream that doesn't work?

**Comment by mikey0000** [comment]
I don't know I've been fighting different fires for the past week

**Comment by quantummobile** [comment]
> I don't know I've been fighting different fires for the past week

Sorry for that. Is there any chance you will take on this issue any time soon?

**Comment by mikey0000** [comment]
> > I don't know I've been fighting different fires for the past week
> 
> Sorry for that. Is there any chance you will take on this issue any time soon?

I'll get to it when I get to it

**Comment by quantummobile** [comment]
> > > I don't know I've been fighting different fires for the past week
> > 
> > 
> > Sorry for that. Is there any chance you will take on this issue any time soon?
> 
> I'll get to it when I get to it

Alright, thanks.
Cheers

**Comment by Suedschwede66** [comment]
v0.5.31 is working

<img width="1585" height="921" alt="Image" src="https://github.com/user-attachments/assets/0d84b4de-5460-4ee5-a098-47b119a170ea" />

**Comment by Guigui37** [comment]
Not working here with a Yuka mini 2 and v0.5.31

<img width="1024" height="590" alt="Image" src="https://github.com/user-attachments/assets/22937c9d-7911-471d-b080-e2de9ca49b65" />

**Comment by myevit** [comment]
Same. 
Mower: LUBA mini AWD 800H
Model entity attr: Luba-MNVTQ9BG
Firmware: 1.15.20.4303
Mammotion-HA: v0.5.38
HA Core: 2026.4.4
camera.lwn_e state: streaming
get_tokens: succeeds
mammotion.refresh_stream: succeeds
mammotion.start_video: succeeds
Frontend error: failed to start WebRTC stream
Fresh HA log: custom_components.mammotion.agora_websocket - WebSocket closed in message loop: no close frame received or sent

**Comment by quantummobile** [comment]
> Not working here with a Yuka mini 2 and v0.5.31
> 
> <img alt="Image" width="1024" height="590" src="https://private-user-images.githubusercontent.com/15849830/587248910-22937c9d-7911-471d-b080-e2de9ca49b65.jpeg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzc5NzEyMzksIm5iZiI6MTc3Nzk3MDkzOSwicGF0aCI6Ii8xNTg0OTgzMC81ODcyNDg5MTAtMjI5MzdjOWQtNzkxMS00NzFkLWIwODAtZTJkZTljYTQ5YjY1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDUwNVQwODQ4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjU4OThiZWQwZGVlZmEyMDFjOWQ1Y2I4ZTE4MjQ5NDFmNDM2MzI5MzgyMGY5NWY5YzY4OThkODRlMzgwOGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZqcGVnIn0.jL24sIo7hsz0ENAjbx9EFHLRa14pLNrGYVbkV_5Mv4A">

Still doesn’t work with Yuka Mini 800 and Firmware: 1.15.20.2303
Addon Version 0.5.31

**Comment by serpentes80** [comment]
I'm getting 
Failed to start WebRTC stream: No stream data available for WebRTC offer

on my yuka mini 700 with version 0.5.38. had 0.5.31 before, same issue

**Comment by mikey0000** [comment]
> Failed to start WebRTC stream: No stream data available for WebRTC offer

doesn't work on Firefox

**Comment by serpentes80** [comment]
> > Failed to start WebRTC stream: No stream data available for WebRTC offer
> 
> doesn't work on Firefox

that would be OK.
But I'm using Brave (Chrome based Browser) or Chrome itself.
Neither is working

**Comment by mperny** [comment]
Hi, I've confirmed that the latest version where video streaming works for me is 5.38 -in newer versions, including 5.40, the error "Action mammotion.start_video not found" is reported. (YUKA mini 2 1000) After downgrading back to 5.38, everything is working again.

**Comment by mikey0000** [comment]
Does the camera entity work?

**Comment by mperny** [comment]
> Does the camera entity work?

The integration component itself never worked for me — I always used a workaround based on the instructions for the "camera-agora-card"

**Comment by serpentes80** [comment]
> Does the camera entity work?

not for me.
neither the integration entity itself, nor the agora-card.
same issue on 2 different home assistant instances

**Comment by 314PierreYves** [comment]
> Does the camera entity work?

Not for me too. I will try to capture logs tomorrow morning.

**Comment by serpentes80** [comment]
with 0.5.40:

<img width="601" height="527" alt="Image" src="https://github.com/user-attachments/assets/68e2881c-a3b0-4cfa-8512-c8c15ff98375" />


with 0.5.14:

<img width="749" height="566" alt="Image" src="https://github.com/user-attachments/assets/eeb3b714-39ac-4e34-8943-4fc620d37c56" />

**Comment by mperny** [comment]
I just tried installing update 5.41-beta1, and the video stream is working again for me after the update

**Comment by oneteam2win** [comment]
Unfortunately, the video isn't working for me.
The message in the video window just keeps saying "Connecting..." forever. This happens in both Microsoft Edge and on Android.
It's also not possible to start the stream directly via the device integration.
It does work in the Mammotion app, though.
Yuka 2024
Integration 0,5,41

**Comment by serpentes80** [comment]
no video with 0.5.43 - still :-(

**Comment by cavox** [comment]
Same for me, when i try to connect to the mammotion app on the smarthpone with the account used by HA, i get the error : "Your account is abnormal and has beend desactivated".
May be that it's the issue

**Comment by bogaczl** [comment]
> Same for me, when i try to connect to the mammotion app on the smarthpone with the account used by HA, i get the error : "Your account is abnormal and has beend desactivated". May be that it's the issue

It’s not related. In my case the camera hasn’t worked for several releases either, but my account is no longer blocked and the camera works fine in the mammotion app. So the issue seems to be somewhere else.

**Comment by Guigui37** [comment]
Just updated to 0.5.44, and now I got very quickly the following message:
"Failed to start WebRTC stream: No stream data available for WebRTC offer"

**Comment by mikey0000** [comment]
> Just updated to 0.5.44, and now I got very quickly the following message: "Failed to start WebRTC stream: No stream data available for WebRTC offer"

Using Firefox?

**Comment by Guigui37** [comment]
> > Just updated to 0.5.44, and now I got very quickly the following message: "Failed to start WebRTC stream: No stream data available for WebRTC offer"
> 
> Using Firefox?

Sorry: on the Android App (and also on Firefox, but I understood it will never work on it)

**Comment by mikey0000** [comment]
Yeah doesn't work on Firefox, don't know why it's stopped working. Will investigate eventually

**Comment by mperny** [comment]
For your information on my end : v 0.5.44 / Chrome / "camera-agora-card" / Yuka mini 2 1000 — the video stream is working

**Comment by mikey0000** [comment]
> For your information on my end : v 0.5.44 / Chrome / "camera-agora-card" / Yuka mini 2 1000 — the video stream is working

Yup I know, took a look today, don't know why it's not working in the native....

**Comment by serpentes80** [comment]
0.5.44 with the agora-card
the video steam is working again for me

**Comment by mikey0000** [comment]
fixed in the beta

**Comment by Hiva-a** [comment]
I just dowloaded your latest beta but I am still getting the following error when i try to see the cameea feed:

"Failed to perform the action mammotion/refresh_stream. 'NoneType' object has no attribute 'attributes'"

By the way, thanks for the amazing work. Much appreciated.

**Comment by mikey0000** [comment]
> I just dowloaded your latest beta but I am still getting the following error when i try to see the cameea feed:
> 
> "Failed to perform the action mammotion/refresh_stream. 'NoneType' object has no attribute 'attributes'"
> 
> By the way, thanks for the amazing work. Much appreciated.

your using the agora card and its likely not pointing to the correct entity nothing to do with the camera entity, it doesn't use that function

**Comment by mperny** [comment]
Hi, I can confirm that the video stream works in version 5.45.beta5—it works both, directly through the entity and via the Agora card (sometimes it's needed to launch the app to view/start the video)

**Comment by quantummobile** [comment]
Doesn’t work even with the latest beta.

**Comment by quantummobile** [comment]
> fixed in the beta

It is not.

**Comment by Guigui37** [comment]
Not fixed in 0.5.45-beta5.

**Comment by Camp3r** [comment]
Pls Check with HA Login if a Login at Mammotion App Are possible or your Account Are blocked.

**Comment by bogaczl** [comment]
Confirming — the 0.5.45‑beta5 release fixes the camera issue for me (Luba Mini AWD 800).

**Comment by quantummobile** [comment]
To whom it may concern - I have noticed that if I stream video in Mammotion native app, video in HA also starts streaming. If I close Mammotion app or stop streaming in the app - stream also stops in HA. Hope this helps.
@mikey0000
