### ISSUE TITLE
Error setting up entry Luba-XXXXXXXX for mammotion

### ISSUE THREAD

**Issue by masp79** [mikey0000/Mammotion-HA#104]
### The problem

After installing Mammotion integration and entering e-mail and password I'm getting error message that integration is unable to start. Account is not a Google account and verified working by signing in to mobile app. 

The log show the following:

Error setting up entry Luba-XXXXXXXX for mammotion
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/__init__.py", line 59, in async_setup_entry
    await mammotion_coordinator.async_setup()
  File "/config/custom_components/mammotion/coordinator.py", line 114, in async_setup
    device.cloud().on_ready_callback = lambda: device.cloud().start_sync(0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'on_ready_callback'

This error is the same regardless if "Use wiFi" is checked or not during setup phase of the integration.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.18

### What version of Home Assistant Core are you running?

core-2024.8.3

**Comment by mikey0000** [comment]
Try reloading the integration, I'll address that issue but it indicates that the integration failed to connect to mammotion / MQTT

**Comment by mikey0000** [comment]
newest version should now throw an error if neither bluetooth or cloud are setup properly, also an issue with the config flow was fixed that may address this too. 0.1.20

**Comment by masp79** [comment]
Thank you very much. After the upgrade to 0.1.20 I also had to reconfigure the integration for it to start working, just restarting didn't help. I guess this is likely related to the change in the config flow?  I can confirm that its working now using BT or Wifi.
