### ISSUE TITLE
Failed setup after upgrade to 0.1.20

### ISSUE THREAD

**Issue by nijel** [mikey0000/Mammotion-HA#105]
### The problem

The integration fails to start now:

```
2024-09-04 07:55:41.920 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Luba-XXXXXX for mammotion
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/__init__.py", line 59, in async_setup_entry
    await mammotion_coordinator.async_setup()
  File "/config/custom_components/mammotion/coordinator.py", line 125, in async_setup
    elif device.ble():
         ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ble'
```

Not using Bluetooth at all, only Wi-Fi.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.20

### What version of Home Assistant Core are you running?

core-2024.8.3

**Comment by nijel** [comment]
https://github.com/mikey0000/Mammotion-HA/pull/106 fixes the crash, but still the setup now fails with *No configuration available to setup Mammotion lawn mower*. It worked fine before the upgrade.

**Comment by mikey0000** [comment]
Can you try reconfigure?

**Comment by nijel** [comment]
It behaves the same when I remove the device and configure it from the scratch.

**Comment by mikey0000** [comment]
I've binned the release for now. Will fix it ASAP

**Comment by nijel** [comment]
The issue is that Use Wi-Fi checkbox was not shown in the config flow and thus `CONF_USE_WIFI` is not configured and this always resorts to using Bluetooth:

https://github.com/mikey0000/Mammotion-HA/blob/9e07e3bd03059e329a5543f9f9ff19a9281778a3/custom_components/mammotion/coordinator.py#L68

Replacing it with `preference = ConnectionPreference.WIFI` makes it work.

Also, when looking at pymammotion changes, there are missing parenthesis in `pymammotion/mammotion/devices/mammotion.py`, but the latest release is not yet on GitHub, so I can't make a pull request to fix that:

```patch
--- pymammotion/mammotion/devices/mammotion.py
+++ pymammotion/mammotion/devices/mammotion.py
@@ -199,7 +199,7 @@
     preference: ConnectionPreference = ConnectionPreference.BLUETOOTH):
     mammotion = Mammotion(ble_device, preference)
 
-    if cloud_credentials and preference == ConnectionPreference.EITHER or preference == ConnectionPreference.WIFI:
+    if cloud_credentials and (preference == ConnectionPreference.EITHER or preference == ConnectionPreference.WIFI):
         cloud_client = await Mammotion.login(cloud_credentials.account_id or cloud_credentials.email,
                                              cloud_credentials.password)
         await mammotion.initiate_cloud_connection(cloud_client)
```

**Comment by mikey0000** [comment]
Right found the issue. Was a configuration not being set properly. All a bit flaky so I'm going to spend some time tidying it up

**Comment by mikey0000** [comment]
> The issue is that Use Wi-Fi checkbox was not shown in the config flow and thus `CONF_USE_WIFI` is not configured and this always resorts to using Bluetooth:
> 
> https://github.com/mikey0000/Mammotion-HA/blob/9e07e3bd03059e329a5543f9f9ff19a9281778a3/custom_components/mammotion/coordinator.py#L68
> 
> Replacing it with `preference = ConnectionPreference.WIFI` makes it work.
> 
> Also, when looking at pymammotion changes, there are missing parenthesis in `pymammotion/mammotion/devices/mammotion.py`, but the latest release is not yet on GitHub, so I can't make a pull request to fix that:
> 
> ```diff
> --- pymammotion/mammotion/devices/mammotion.py
> +++ pymammotion/mammotion/devices/mammotion.py
> @@ -199,7 +199,7 @@
>      preference: ConnectionPreference = ConnectionPreference.BLUETOOTH):
>      mammotion = Mammotion(ble_device, preference)
>  
> -    if cloud_credentials and preference == ConnectionPreference.EITHER or preference == ConnectionPreference.WIFI:
> +    if cloud_credentials and (preference == ConnectionPreference.EITHER or preference == ConnectionPreference.WIFI):
>          cloud_client = await Mammotion.login(cloud_credentials.account_id or cloud_credentials.email,
>                                               cloud_credentials.password)
>          await mammotion.initiate_cloud_connection(cloud_client)
> ```

Yeah the issue is conf wifi wasn't being set to a default for just wifi

**Comment by mikey0000** [comment]
Pushed out a fix

**Comment by mikey0000** [comment]
You will need to remove your mower and readd it to fix the problem once on 0.1.21

**Comment by nijel** [comment]
It works even without that.

**Comment by mikey0000** [comment]
Sweet
